### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by vanelnw** [vanelnw/vanelnw.github.io#7]

**Comment by sebalp100** [comment]
Your code is looking great. Very organized.
I think it would be better to remove the "required" from the HTML form and use the code from your javascript to validate.

**Comment by jellywiz** [comment]
Hi there Vanel 
the code looks clean and so far you have done so much well done!🔥You have made so far with the JavaScript 

- My only concern would be the design it looks similar with the figma design, and I believe you are talented and make it as close as the figma design.

Again Well-done!

**Comment by dialite** [comment]
Having gone through your code, I see your level of commitment is high. Keep it up

**Comment by vanelnw** [comment]
> Your code is looking great. Very organized. I think it would be better to remove the "required" from the HTML form and use the code from your javascript to validate.

Hi @sebalp100, :wave:

Thank you for your positive feedback on the code organization. I appreciate your suggestion to remove the "required" attribute from the HTML form and use JavaScript for validation. I will definitely consider this approach as I continue to optimize the form. Thank you for taking the time to provide your insights and ideas.

**Comment by vanelnw** [comment]
> Hi there Vanel 
> the code looks clean and so far you have done so much well done!🔥You have made so far with the JavaScript
> 
> * My only concern would be the design it looks similar with the figma design, and I believe you are talented and make it as close as the figma design.
> 
> Again Well-done!

Hi @jellywiz, :wave:
Thank you for your kind words and encouragement!  I'm glad to hear that you think it looks clean and that I've done well with the JavaScript so far. I appreciate your feedback on the design and agree that it's important to strive for as close a match as possible to the figma design. I will definitely make an effort to ensure that the design is as close to the figma design as possible. Thank you again for your support and encouragement.

**Comment by vanelnw** [comment]
> Having gone through your code, I see your level of commitment is high. Keep it up

Hi @dialite, 👋 

Thank you so much for your kind words and encouragement! I'm glad to hear that you think I am committed to my work, and I appreciate your support.Thank you again for your feedback and for taking the time to review my code. I appreciate your support and guidance.
